--------------------------------------------------------
--  파일이 생성됨 - 금요일-12월-29-2023   
--------------------------------------------------------
DROP SEQUENCE "GUYS"."SEQ_TB_COMMENT_NO";
DROP SEQUENCE "GUYS"."SEQ_TB_CONVEN_NO";
DROP SEQUENCE "GUYS"."SEQ_TB_MENU_NO";
DROP SEQUENCE "GUYS"."SEQ_TB_MENU_PIC_NO";
DROP SEQUENCE "GUYS"."SEQ_TB_RESERV_NO";
DROP SEQUENCE "GUYS"."SEQ_TB_REST_NO";
DROP SEQUENCE "GUYS"."SEQ_TB_REVIEW_NO";
DROP SEQUENCE "GUYS"."SEQ_TB_REVIEW_PIC_NO";
DROP SEQUENCE "GUYS"."SEQ_TB_USER_USER_NO";
DROP TABLE "GUYS"."TB_ATTRACTION" cascade constraints;
DROP TABLE "GUYS"."TB_CONVENIENCE" cascade constraints;
DROP TABLE "GUYS"."TB_MENU" cascade constraints;
DROP TABLE "GUYS"."TB_MENU_PICTURE" cascade constraints;
DROP TABLE "GUYS"."TB_RESERVATION" cascade constraints;
DROP TABLE "GUYS"."TB_RESTAURANT" cascade constraints;
DROP TABLE "GUYS"."TB_REVIEW" cascade constraints;
DROP TABLE "GUYS"."TB_REVIEW_PICTURE" cascade constraints;
DROP TABLE "GUYS"."TB_USER" cascade constraints;
DROP TABLE "GUYS"."TB_RESTAURANT" cascade constraints;
DROP TABLE "GUYS"."TB_MENU" cascade constraints;
DROP TABLE "GUYS"."TB_USER" cascade constraints;
DROP TABLE "GUYS"."TB_REVIEW" cascade constraints;
DROP TABLE "GUYS"."TB_ATTRACTION" cascade constraints;
DROP TABLE "GUYS"."TB_CONVENIENCE" cascade constraints;
DROP TABLE "GUYS"."TB_MENU_PICTURE" cascade constraints;
DROP TABLE "GUYS"."TB_RESERVATION" cascade constraints;
DROP TABLE "GUYS"."TB_REVIEW_PICTURE" cascade constraints;
--------------------------------------------------------
--  DDL for Sequence SEQ_TB_COMMENT_NO
--------------------------------------------------------

   CREATE SEQUENCE  "GUYS"."SEQ_TB_COMMENT_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TB_CONVEN_NO
--------------------------------------------------------

   CREATE SEQUENCE  "GUYS"."SEQ_TB_CONVEN_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TB_MENU_NO
--------------------------------------------------------

   CREATE SEQUENCE  "GUYS"."SEQ_TB_MENU_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TB_MENU_PIC_NO
--------------------------------------------------------

   CREATE SEQUENCE  "GUYS"."SEQ_TB_MENU_PIC_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TB_RESERV_NO
--------------------------------------------------------

   CREATE SEQUENCE  "GUYS"."SEQ_TB_RESERV_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TB_REST_NO
--------------------------------------------------------

   CREATE SEQUENCE  "GUYS"."SEQ_TB_REST_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TB_REVIEW_NO
--------------------------------------------------------

   CREATE SEQUENCE  "GUYS"."SEQ_TB_REVIEW_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TB_REVIEW_PIC_NO
--------------------------------------------------------

   CREATE SEQUENCE  "GUYS"."SEQ_TB_REVIEW_PIC_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TB_USER_USER_NO
--------------------------------------------------------

   CREATE SEQUENCE  "GUYS"."SEQ_TB_USER_USER_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table TB_ATTRACTION
--------------------------------------------------------

  CREATE TABLE "GUYS"."TB_ATTRACTION" 
   (	"USER_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"REST_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TB_CONVENIENCE
--------------------------------------------------------

  CREATE TABLE "GUYS"."TB_CONVENIENCE" 
   (	"CONVEN_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"CONVEN_KIND" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TB_MENU
--------------------------------------------------------

  CREATE TABLE "GUYS"."TB_MENU" 
   (	"MENU_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"REST_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"MENU_NAME" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"MENU_CONTENT" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP", 
	"MENU_PRICE" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TB_MENU_PICTURE
--------------------------------------------------------

  CREATE TABLE "GUYS"."TB_MENU_PICTURE" 
   (	"MENU_PIC_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"MENU_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"MENU_PIC_RENAMED_FILENAME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TB_RESERVATION
--------------------------------------------------------

  CREATE TABLE "GUYS"."TB_RESERVATION" 
   (	"RESERV_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"REST_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"RESERV_NAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"RESERV_DATE" DATE, 
	"RESERV_TIME" DATE, 
	"RESERV_PEOPLE" NUMBER DEFAULT 2, 
	"RESERV_REQ" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"RESERV_REG_DATE" DATE DEFAULT sysdate
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TB_RESTAURANT
--------------------------------------------------------

  CREATE TABLE "GUYS"."TB_RESTAURANT" 
   (	"REST_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"REST_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"REST_ADDRESS" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"REST_CONTENT" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP", 
	"REST_PHONE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"REST_CATEGORY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"REST_OPEN_TIME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"REST_CLOSE_TIME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"REST_RESERV" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y', 
	"REST_RESERV_TIME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"REST_TOTAL_STAR" NUMBER, 
	"REST_CREATED_DATE" DATE DEFAULT sysdate
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TB_REVIEW
--------------------------------------------------------

  CREATE TABLE "GUYS"."TB_REVIEW" 
   (	"REVIEW_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"REST_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"REVIEW_CONTENT" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP", 
	"REVIEW_STAR_GRADE" NUMBER, 
	"REVIEW_REG_DATE" DATE DEFAULT sysdate
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TB_REVIEW_PICTURE
--------------------------------------------------------

  CREATE TABLE "GUYS"."TB_REVIEW_PICTURE" 
   (	"REVIEW_PIC_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"REVIEW_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"REVIEW_PIC_RENAMED_FILENAME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"REVIEW_PIC_REG_DATE" DATE DEFAULT sysdate
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TB_USER
--------------------------------------------------------

  CREATE TABLE "GUYS"."TB_USER" 
   (	"USER_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_PASSWORD" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_NAME" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_NICKNAME" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_GENDER" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'M', 
	"USER_EMAIL" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_PHONE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_ROLE" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'U', 
	"USER_CATEGORY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_CREATED_DATE" DATE DEFAULT sysdate
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TB_RESTAURANT
--------------------------------------------------------

  CREATE TABLE "GUYS"."TB_RESTAURANT" 
   (	"REST_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"REST_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"REST_ADDRESS" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"REST_CONTENT" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP", 
	"REST_PHONE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"REST_CATEGORY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"REST_OPEN_TIME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"REST_CLOSE_TIME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"REST_RESERV" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y', 
	"REST_RESERV_TIME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"REST_TOTAL_STAR" NUMBER, 
	"REST_CREATED_DATE" DATE DEFAULT sysdate
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TB_MENU
--------------------------------------------------------

  CREATE TABLE "GUYS"."TB_MENU" 
   (	"MENU_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"REST_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"MENU_NAME" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"MENU_CONTENT" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP", 
	"MENU_PRICE" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TB_USER
--------------------------------------------------------

  CREATE TABLE "GUYS"."TB_USER" 
   (	"USER_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_PASSWORD" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_NAME" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_NICKNAME" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_GENDER" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'M', 
	"USER_EMAIL" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_PHONE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_ROLE" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'U', 
	"USER_CATEGORY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_CREATED_DATE" DATE DEFAULT sysdate
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TB_REVIEW
--------------------------------------------------------

  CREATE TABLE "GUYS"."TB_REVIEW" 
   (	"REVIEW_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"REST_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"REVIEW_CONTENT" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP", 
	"REVIEW_STAR_GRADE" NUMBER, 
	"REVIEW_REG_DATE" DATE DEFAULT sysdate
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TB_ATTRACTION
--------------------------------------------------------

  CREATE TABLE "GUYS"."TB_ATTRACTION" 
   (	"USER_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"REST_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TB_CONVENIENCE
--------------------------------------------------------

  CREATE TABLE "GUYS"."TB_CONVENIENCE" 
   (	"CONVEN_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"CONVEN_KIND" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TB_MENU_PICTURE
--------------------------------------------------------

  CREATE TABLE "GUYS"."TB_MENU_PICTURE" 
   (	"MENU_PIC_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"MENU_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"MENU_PIC_RENAMED_FILENAME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TB_RESERVATION
--------------------------------------------------------

  CREATE TABLE "GUYS"."TB_RESERVATION" 
   (	"RESERV_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"REST_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"RESERV_NAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"RESERV_DATE" DATE, 
	"RESERV_TIME" DATE, 
	"RESERV_PEOPLE" NUMBER DEFAULT 2, 
	"RESERV_REQ" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"RESERV_REG_DATE" DATE DEFAULT sysdate
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TB_REVIEW_PICTURE
--------------------------------------------------------

  CREATE TABLE "GUYS"."TB_REVIEW_PICTURE" 
   (	"REVIEW_PIC_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"REVIEW_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"REVIEW_PIC_RENAMED_FILENAME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"REVIEW_PIC_REG_DATE" DATE DEFAULT sysdate
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
REM INSERTING into GUYS.TB_ATTRACTION
SET DEFINE OFF;
REM INSERTING into GUYS.TB_CONVENIENCE
SET DEFINE OFF;
REM INSERTING into GUYS.TB_MENU
SET DEFINE OFF;
Insert into GUYS.TB_MENU (MENU_NO,REST_NO,MENU_NAME,MENU_CONTENT,MENU_PRICE) values ('21','rest002','떡볶이','고추장을 떡과 볶아서 먹는 맛있는 한국 요리',3000);
REM INSERTING into GUYS.TB_MENU_PICTURE
SET DEFINE OFF;
REM INSERTING into GUYS.TB_RESERVATION
SET DEFINE OFF;
REM INSERTING into GUYS.TB_RESTAURANT
SET DEFINE OFF;
Insert into GUYS.TB_RESTAURANT (REST_NO,USER_NO,REST_NAME,REST_ADDRESS,REST_CONTENT,REST_PHONE,REST_CATEGORY,REST_OPEN_TIME,REST_CLOSE_TIME,REST_RESERV,REST_RESERV_TIME,REST_TOTAL_STAR,REST_CREATED_DATE) values ('rest002','user021','샘플 식당','강남구 kh정보교육원','샘플 데이터 입니다.','02-3391-4991','it','9:00','18:00','Y','9:00',5,to_date('2023/12/28 11:01:24','RRRR/MM/DD HH24:MI:SS'));
Insert into GUYS.TB_RESTAURANT (REST_NO,USER_NO,REST_NAME,REST_ADDRESS,REST_CONTENT,REST_PHONE,REST_CATEGORY,REST_OPEN_TIME,REST_CLOSE_TIME,REST_RESERV,REST_RESERV_TIME,REST_TOTAL_STAR,REST_CREATED_DATE) values ('rest003','user021','샘플 식당2','강남구 kh정보교육원 3관','샘플 데이터2 입니다.','02-1191-1911','it','9:00','18:00','Y','9:00',5,to_date('2023/12/28 16:17:38','RRRR/MM/DD HH24:MI:SS'));
REM INSERTING into GUYS.TB_REVIEW
SET DEFINE OFF;
REM INSERTING into GUYS.TB_REVIEW_PICTURE
SET DEFINE OFF;
REM INSERTING into GUYS.TB_USER
SET DEFINE OFF;
Insert into GUYS.TB_USER (USER_NO,USER_ID,USER_PASSWORD,USER_NAME,USER_NICKNAME,USER_GENDER,USER_EMAIL,USER_PHONE,USER_ROLE,USER_CATEGORY,USER_CREATED_DATE) values ('user021','woojin','woojin','오우진','우진','M','woojin@gmail.com','010-1234-1231','M',null,to_date('2023/12/28 10:55:23','RRRR/MM/DD HH24:MI:SS'));
Insert into GUYS.TB_USER (USER_NO,USER_ID,USER_PASSWORD,USER_NAME,USER_NICKNAME,USER_GENDER,USER_EMAIL,USER_PHONE,USER_ROLE,USER_CATEGORY,USER_CREATED_DATE) values ('user023','leejj','1234','이재준','재준','M','leejj3240@gmail.com','01096984252','U',null,to_date('2023/12/28 11:18:52','RRRR/MM/DD HH24:MI:SS'));
--------------------------------------------------------
--  DDL for Index PK_TB_ATTRACTION_USER_REST_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUYS"."PK_TB_ATTRACTION_USER_REST_NO" ON "GUYS"."TB_ATTRACTION" ("USER_NO", "REST_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index PK_TB_CONVENIENCE_CONVEN_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUYS"."PK_TB_CONVENIENCE_CONVEN_NO" ON "GUYS"."TB_CONVENIENCE" ("CONVEN_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index PK_TB_MENU_MENU_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUYS"."PK_TB_MENU_MENU_NO" ON "GUYS"."TB_MENU" ("MENU_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index PK_TB_MENU_PICTURE_MENU_PIC_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUYS"."PK_TB_MENU_PICTURE_MENU_PIC_NO" ON "GUYS"."TB_MENU_PICTURE" ("MENU_PIC_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index PK_TB_RESERVATION_RESERV_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUYS"."PK_TB_RESERVATION_RESERV_NO" ON "GUYS"."TB_RESERVATION" ("RESERV_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index PK_TB_REST_REST_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUYS"."PK_TB_REST_REST_NO" ON "GUYS"."TB_RESTAURANT" ("REST_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index PK_TB_REVIEW_PICTURE_REVIEW_PIC_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUYS"."PK_TB_REVIEW_PICTURE_REVIEW_PIC_NO" ON "GUYS"."TB_REVIEW_PICTURE" ("REVIEW_PIC_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index PK_TB_REVIEW_REVIEW_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUYS"."PK_TB_REVIEW_REVIEW_NO" ON "GUYS"."TB_REVIEW" ("REVIEW_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index PK_TB_USER_USER_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUYS"."PK_TB_USER_USER_NO" ON "GUYS"."TB_USER" ("USER_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index UQ_TB_REST_REST_PHONE
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUYS"."UQ_TB_REST_REST_PHONE" ON "GUYS"."TB_RESTAURANT" ("REST_PHONE") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index UQ_TB_USER_USER_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUYS"."UQ_TB_USER_USER_ID" ON "GUYS"."TB_USER" ("USER_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index UQ_TB_USER_USER_NICKNAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUYS"."UQ_TB_USER_USER_NICKNAME" ON "GUYS"."TB_USER" ("USER_NICKNAME") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index UQ_TB_USER_USER_PHONE
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUYS"."UQ_TB_USER_USER_PHONE" ON "GUYS"."TB_USER" ("USER_PHONE") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index PK_TB_ATTRACTION_USER_REST_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUYS"."PK_TB_ATTRACTION_USER_REST_NO" ON "GUYS"."TB_ATTRACTION" ("USER_NO", "REST_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index PK_TB_CONVENIENCE_CONVEN_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUYS"."PK_TB_CONVENIENCE_CONVEN_NO" ON "GUYS"."TB_CONVENIENCE" ("CONVEN_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index PK_TB_MENU_MENU_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUYS"."PK_TB_MENU_MENU_NO" ON "GUYS"."TB_MENU" ("MENU_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index PK_TB_MENU_PICTURE_MENU_PIC_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUYS"."PK_TB_MENU_PICTURE_MENU_PIC_NO" ON "GUYS"."TB_MENU_PICTURE" ("MENU_PIC_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index PK_TB_RESERVATION_RESERV_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUYS"."PK_TB_RESERVATION_RESERV_NO" ON "GUYS"."TB_RESERVATION" ("RESERV_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index PK_TB_REST_REST_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUYS"."PK_TB_REST_REST_NO" ON "GUYS"."TB_RESTAURANT" ("REST_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index UQ_TB_REST_REST_PHONE
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUYS"."UQ_TB_REST_REST_PHONE" ON "GUYS"."TB_RESTAURANT" ("REST_PHONE") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index PK_TB_REVIEW_REVIEW_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUYS"."PK_TB_REVIEW_REVIEW_NO" ON "GUYS"."TB_REVIEW" ("REVIEW_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index PK_TB_REVIEW_PICTURE_REVIEW_PIC_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUYS"."PK_TB_REVIEW_PICTURE_REVIEW_PIC_NO" ON "GUYS"."TB_REVIEW_PICTURE" ("REVIEW_PIC_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index PK_TB_USER_USER_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUYS"."PK_TB_USER_USER_NO" ON "GUYS"."TB_USER" ("USER_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index UQ_TB_USER_USER_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUYS"."UQ_TB_USER_USER_ID" ON "GUYS"."TB_USER" ("USER_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index UQ_TB_USER_USER_NICKNAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUYS"."UQ_TB_USER_USER_NICKNAME" ON "GUYS"."TB_USER" ("USER_NICKNAME") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index UQ_TB_USER_USER_PHONE
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUYS"."UQ_TB_USER_USER_PHONE" ON "GUYS"."TB_USER" ("USER_PHONE") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table TB_ATTRACTION
--------------------------------------------------------

  ALTER TABLE "GUYS"."TB_ATTRACTION" MODIFY ("USER_NO" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_ATTRACTION" MODIFY ("REST_NO" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_ATTRACTION" ADD CONSTRAINT "PK_TB_ATTRACTION_USER_REST_NO" PRIMARY KEY ("USER_NO", "REST_NO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_CONVENIENCE
--------------------------------------------------------

  ALTER TABLE "GUYS"."TB_CONVENIENCE" MODIFY ("CONVEN_NO" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_CONVENIENCE" ADD CONSTRAINT "PK_TB_CONVENIENCE_CONVEN_NO" PRIMARY KEY ("CONVEN_NO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_MENU
--------------------------------------------------------

  ALTER TABLE "GUYS"."TB_MENU" MODIFY ("MENU_NO" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_MENU" MODIFY ("REST_NO" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_MENU" MODIFY ("MENU_NAME" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_MENU" MODIFY ("MENU_PRICE" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_MENU" ADD CONSTRAINT "PK_TB_MENU_MENU_NO" PRIMARY KEY ("MENU_NO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_MENU_PICTURE
--------------------------------------------------------

  ALTER TABLE "GUYS"."TB_MENU_PICTURE" MODIFY ("MENU_PIC_NO" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_MENU_PICTURE" MODIFY ("MENU_NO" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_MENU_PICTURE" MODIFY ("MENU_PIC_RENAMED_FILENAME" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_MENU_PICTURE" ADD CONSTRAINT "PK_TB_MENU_PICTURE_MENU_PIC_NO" PRIMARY KEY ("MENU_PIC_NO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_RESERVATION
--------------------------------------------------------

  ALTER TABLE "GUYS"."TB_RESERVATION" MODIFY ("RESERV_NO" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_RESERVATION" MODIFY ("REST_NO" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_RESERVATION" MODIFY ("USER_NO" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_RESERVATION" MODIFY ("RESERV_NAME" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_RESERVATION" MODIFY ("RESERV_DATE" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_RESERVATION" MODIFY ("RESERV_TIME" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_RESERVATION" MODIFY ("RESERV_PEOPLE" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_RESERVATION" MODIFY ("RESERV_REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_RESERVATION" ADD CONSTRAINT "PK_TB_RESERVATION_RESERV_NO" PRIMARY KEY ("RESERV_NO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_RESTAURANT
--------------------------------------------------------

  ALTER TABLE "GUYS"."TB_RESTAURANT" MODIFY ("REST_NO" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_RESTAURANT" MODIFY ("USER_NO" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_RESTAURANT" MODIFY ("REST_NAME" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_RESTAURANT" MODIFY ("REST_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_RESTAURANT" MODIFY ("REST_PHONE" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_RESTAURANT" MODIFY ("REST_CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_RESTAURANT" MODIFY ("REST_OPEN_TIME" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_RESTAURANT" MODIFY ("REST_CLOSE_TIME" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_RESTAURANT" MODIFY ("REST_RESERV" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_RESTAURANT" MODIFY ("REST_RESERV_TIME" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_RESTAURANT" MODIFY ("REST_CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_RESTAURANT" ADD CONSTRAINT "CK_TB_REST_REST_RESERV" CHECK (rest_reserv in ('Y', 'N')) ENABLE;
  ALTER TABLE "GUYS"."TB_RESTAURANT" ADD CONSTRAINT "PK_TB_REST_REST_NO" PRIMARY KEY ("REST_NO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "GUYS"."TB_RESTAURANT" ADD CONSTRAINT "UQ_TB_REST_REST_PHONE" UNIQUE ("REST_PHONE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_REVIEW
--------------------------------------------------------

  ALTER TABLE "GUYS"."TB_REVIEW" MODIFY ("REVIEW_NO" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_REVIEW" MODIFY ("REST_NO" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_REVIEW" MODIFY ("USER_NO" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_REVIEW" MODIFY ("REVIEW_REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_REVIEW" ADD CONSTRAINT "CK_TB_REVIEW_REVIEW_STAR_GRADE" CHECK (review_star_grade in(1, 2, 3, 4, 5)) ENABLE;
  ALTER TABLE "GUYS"."TB_REVIEW" ADD CONSTRAINT "PK_TB_REVIEW_REVIEW_NO" PRIMARY KEY ("REVIEW_NO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_REVIEW_PICTURE
--------------------------------------------------------

  ALTER TABLE "GUYS"."TB_REVIEW_PICTURE" MODIFY ("REVIEW_PIC_NO" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_REVIEW_PICTURE" MODIFY ("REVIEW_NO" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_REVIEW_PICTURE" ADD CONSTRAINT "PK_TB_REVIEW_PICTURE_REVIEW_PIC_NO" PRIMARY KEY ("REVIEW_PIC_NO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_USER
--------------------------------------------------------

  ALTER TABLE "GUYS"."TB_USER" MODIFY ("USER_NO" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_USER" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_USER" MODIFY ("USER_PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_USER" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_USER" MODIFY ("USER_NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_USER" MODIFY ("USER_PHONE" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_USER" MODIFY ("USER_ROLE" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_USER" MODIFY ("USER_CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "GUYS"."TB_USER" ADD CONSTRAINT "CK_TB_USER_USER_GENDER" CHECK (user_gender in ('M', 'F')) ENABLE;
  ALTER TABLE "GUYS"."TB_USER" ADD CONSTRAINT "CK_TB_USER_USER_ROLE" CHECK (user_role in ('M', 'O', 'U')) ENABLE;
  ALTER TABLE "GUYS"."TB_USER" ADD CONSTRAINT "PK_TB_USER_USER_NO" PRIMARY KEY ("USER_NO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "GUYS"."TB_USER" ADD CONSTRAINT "UQ_TB_USER_USER_ID" UNIQUE ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "GUYS"."TB_USER" ADD CONSTRAINT "UQ_TB_USER_USER_NICKNAME" UNIQUE ("USER_NICKNAME")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "GUYS"."TB_USER" ADD CONSTRAINT "UQ_TB_USER_USER_PHONE" UNIQUE ("USER_PHONE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_MENU
--------------------------------------------------------

  ALTER TABLE "GUYS"."TB_MENU" ADD CONSTRAINT "FK_TB_MENU_REST_NO" FOREIGN KEY ("REST_NO")
	  REFERENCES "GUYS"."TB_RESTAURANT" ("REST_NO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_MENU_PICTURE
--------------------------------------------------------

  ALTER TABLE "GUYS"."TB_MENU_PICTURE" ADD CONSTRAINT "FK_TB_MENU_PICTURE_MENU_NO" FOREIGN KEY ("MENU_NO")
	  REFERENCES "GUYS"."TB_MENU" ("MENU_NO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_RESERVATION
--------------------------------------------------------

  ALTER TABLE "GUYS"."TB_RESERVATION" ADD CONSTRAINT "FK_TB_RESERVATION_REST_NO" FOREIGN KEY ("REST_NO")
	  REFERENCES "GUYS"."TB_RESTAURANT" ("REST_NO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "GUYS"."TB_RESERVATION" ADD CONSTRAINT "FK_TB_RESERVATION_USER_NO" FOREIGN KEY ("USER_NO")
	  REFERENCES "GUYS"."TB_USER" ("USER_NO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_RESTAURANT
--------------------------------------------------------

  ALTER TABLE "GUYS"."TB_RESTAURANT" ADD CONSTRAINT "FK_TB_REST_USER_NO" FOREIGN KEY ("USER_NO")
	  REFERENCES "GUYS"."TB_USER" ("USER_NO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_REVIEW
--------------------------------------------------------

  ALTER TABLE "GUYS"."TB_REVIEW" ADD CONSTRAINT "FK_TB_REVIEW_REST_NO" FOREIGN KEY ("REST_NO")
	  REFERENCES "GUYS"."TB_RESTAURANT" ("REST_NO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "GUYS"."TB_REVIEW" ADD CONSTRAINT "FK_TB_REVIEW_USER_NO" FOREIGN KEY ("USER_NO")
	  REFERENCES "GUYS"."TB_USER" ("USER_NO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_REVIEW_PICTURE
--------------------------------------------------------

  ALTER TABLE "GUYS"."TB_REVIEW_PICTURE" ADD CONSTRAINT "FK_TB_REVIEW_REVIEW_NO" FOREIGN KEY ("REVIEW_NO")
	  REFERENCES "GUYS"."TB_REVIEW" ("REVIEW_NO") ON DELETE CASCADE ENABLE;
